# Generated by Django 3.2.3 on 2021-05-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('password', models.TextField(max_length=30, verbose_name='Password')),
            ],
        ),
    ]
