# Generated by Django 3.2.3 on 2021-05-30 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210530_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='Email')),
                ('password', models.TextField(max_length=30, verbose_name='Password')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
