# Generated by Django 3.2.3 on 2021-05-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210530_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserA',
        ),
    ]
